### ISSUE TITLE
Failing test: recent_unsub_activity_subscriptions(number)

### ISSUE THREAD

**Issue by Sacristan** [CreativePublisher/creative_subscriptions#31]
1) SubscriptionProgressStatistic Scopes .about_unsubscribe should return the stat items pertaining to unsub
     Failure/Error: expect(unsubscribes.size).to eq 6

       expected: 6
            got: 20

       (compared using ==)
     # ./spec/models/subscription_progress_statistic_spec.rb:53:in `block (4 levels) in <top (required)>'

Finished in 4.67 seconds (files took 4.6 seconds to load)
128 examples, 1 failure, 7 pending

Failed examples:

rspec ./spec/models/subscription_progress_statistic_spec.rb:50 # SubscriptionProgressStatistic Scopes .about_unsubscribe should return the stat items pertaining to unsub

**Comment by Sacristan** [comment]
īsti nepalīdz Subscription nodzēšana, kam vajadzētu arī visus datus izlabot.

**Comment by Sacristan** [comment]
please check

**Comment by Epigene** [comment]
Ne Sub, bet testēto objektu -  SubscriptionProgressStatistic - dzēšana

Pieliku klass.destroy_all testa sākumā -> works

Es pieturos pie prakses, ka bottom-most describe bloks (metodes bloks) definē at most vienu `before :each/:all` bloku, kura sākumā es varu saukt klass.destroy_all -> parūpēties, ka DB eksistē tikai testam nepieciešamie objekti.

Ideāli protams būtu, ja nebūtu nepieciešams tīrīt db ar roku pirms/pēc testiem.
